### ISSUE TITLE
authenticator not working (S8+)

### ISSUE THREAD

**Issue by waynenilsen** [maidsafe/safe-email-app-csharp#2]
I could not register with mobile (S8+) and invite code, could not login with account created with browser, both have error -2000. Could not connect to the SAFE Network.

**Comment by ashwinkumar6** [comment]
@waynenilsen  I appolozie for the delay, thanks for reporting the issue. SafeAuthenticator-mobile have been moved to a different respository. This issue has been resolved, Can you try building the safe-authenticator app from [here](https://github.com/maidsafe/safe-authenticator-mobile)

**Comment by ashwinkumar6** [comment]
The latest released version of the safe-authenticator can be found [here](https://github.com/maidsafe/safe-authenticator-mobile/releases)

**Comment by ravinderjangra** [comment]
As the SAFE Authenticator has been moved to a separate dedicated repo. If you still getting the same issue please report in [SAFE Authenticator](https://github.com/maidsafe/safe-authenticator-mobile/releases) repo.
