### ISSUE TITLE
`Auto Reconnect` option fails authentication on < API 19 (<Android v4.4), if enabled

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-email-app-csharp#33]
The auto-reconnect option present in the SAFE Messages authentication page, when turned on is used to store the user's credentials in a secure store on KeyStore and KeyChain for Android and iOS respectively. The library user for this is Xamarin.Essentials. This feature is not supported in Android when the API level <19 (< Android v4.4).
Result of enabling this slider is that the app will fail authentication.
Workaround - set the slider to not auto reconnect

**Comment by ravinderjangra** [comment]
We no longer support Android 5.0 and less.
